- name : Play level vars
  hosts: localhost
  vars:
    URL: Play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name : Vars from files
  hosts: localhost
  vars_files:
     - demo-vars.yml
  tasks:
     - name: Print URL
       ansible.builtin.debug:
         msg: URL = {{ URL }}

- name : Vars from tasks
  hosts: localhost
  tasks:
     - name: Print URL
       ansible.builtin.debug:
         msg: URL = {{ URL }}
       vars:
         URL: tasks.example.com


